fd = open ("dados1.txt", "r")
dados = fd.read(15)
print ("Primeira leitura:", dados)
print ("Estou na posicao ", fd.tell())
fd.seek(10)
print ("Agora estou na posicao ", fd.tell())
dados = fd.read(100)
print ("Segunda leitura:", dados)
fd.close()